# Generated by Django 5.0.6 on 2026-05-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        ('user_sessions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(default='START', max_length=50)),
                ('step_index', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.session')),
            ],
        ),
    ]
