# Generated by Django 5.0.6 on 2026-05-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_question'),
        ('user_sessions', '0003_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='user_sessions.session'),
        ),
    ]
