# Generated by Django 5.0.6 on 2026-05-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_message_session'),
        ('user_sessions', '0003_alter_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_sessions.session'),
        ),
    ]
