# Generated by Django 5.0.6 on 2026-05-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainscore',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='user_sessions.session'),
        ),
    ]
