# Generated by Django 5.0.6 on 2026-05-04 12:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_initial'),
        ('user_sessions', '0003_alter_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurevector',
            name='features',
        ),
        migrations.RemoveField(
            model_name='featurevector',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='featurevector',
            name='analytical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='business',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurevector',
            name='creativity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='research',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='source_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurevector',
            name='technical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='featurevector',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='featurevector',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='user_sessions.session'),
        ),
    ]
