# Generated by Django 5.0.6 on 2026-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('career', 'Career'), ('degree', 'Degree')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
